### PR TITLE
initial release for review

### PR DESCRIPTION
**Pull request by pruthvirajmv**
Hello,

This is the first version of my CSS component library, where I have created simple and useful components
I had my own code review, it seems naming classes are not much consistent. Mixed up with css units.
Request you to provide feedback on class names and also unwanted or better way of styling if any
Other areas to improve...

### CODE REVIEW

**Comment by agauravdev** [comment]
Here are a few observations. 

-> The naming convention that I've seen goes like `alert-success` and not the other way round. 
-> The naming convention is irregular at some places, like you `.avatar.medium` to show a medium sized avatar, but have use `success-alert` for success alert. A good way to prevent this is to use BEM naming convention. 

These were the primary things that I found. 🙈

**Comment by gauravggg21** [comment]
Here are a few observations. 

-> The naming convention that I've seen goes like `alert-success` and not the other way round. 
-> The naming convention is irregular at some places, like you `.avatar.medium` to show a medium sized avatar, but have use `success-alert` for success alert. A good way to prevent this is to use BEM naming convention. 

These were the primary things that I found. 🙈

**Comment by RadhikaRJ** [comment]
Great Work @pruthvirajmv . Displaying code on click of button is brilliant!
Some suggestions:
1. Alerts--> set the border of the alert to a dark shade of the respective background color (instead of black) to make it look prominent.
2. hr tag--> You can space out the component divisions a little more by applying margin-top/margin-bottom property to hr. To apply color to the line displayed by hr tag, you can use border-color property.

**Comment by pruthvirajmv** [comment]
> Here are a few observations.
> 
> -> The naming convention that I've seen goes like `alert-success` and not the other way round.
> -> The naming convention is irregular at some places, like you `.avatar.medium` to show a medium sized avatar, but have use `success-alert` for success alert. A good way to prevent this is to use BEM naming convention.
> 
> These were the primary things that I found. 🙈

Hello Gaurav, now class names are consistent with the hyphen delimited convention. Also, read about BEM convention

**Comment by pruthvirajmv** [comment]
> Great Work @pruthvirajmv . Displaying code on click of button is brilliant!
> Some suggestions:
> 
> 1. Alerts--> set the border of the alert to a dark shade of the respective background color (instead of black) to make it look prominent.
> 2. hr tag--> You can space out the component divisions a little more by applying margin-top/margin-bottom property to hr. To apply color to the line displayed by hr tag, you can use border-color property.

Hello Radhika,
1. Alerts - border colors updated
2. hr tag - have not used hr tag, but I got your point and so have increased the spacings between the components
And the hamburger menu issue has also been fixed
Thanks for your inputs!

**Comment by pruthvirajmv** [comment]
> Here are a few observations.
> 
> -> The naming convention that I've seen goes like `alert-success` and not the other way round.
> -> The naming convention is irregular at some places, like you `.avatar.medium` to show a medium sized avatar, but have use `success-alert` for success alert. A good way to prevent this is to use BEM naming convention.
> 
> These were the primary things that I found. 🙈

Yes, now I have renamed the classes consistently following hyphen delimited convention and read about BEM convention
Thanks for your inputs!

**Comment by sakshijainn** [comment]
Hi 
1. For reference, problem is
image
When I hover to any component , I am not able to get complete content for that component, some part got hidden
I think something like this would look clean:
image


2. For reference:
image
while clicking on hamburger menu, I think whole navbar if occupies entire viewport width and height  that would look more clean such that when you will click any component , the navbar goes off and displays the content for that particular component.

3. Add hover effect on navigation bar li items for visual effect of clicking

4. For reference:
image
The buttons of installation and getStarted if are larger in width , with transparent backgrounds will cover the whitespace and will look visual good


Though I liked your quirky UI and color theme +that code button looks amazing!

**Comment by pruthvirajmv** [comment]
> Hi
> 
> 1. For reference, problem is
>    image
>    When I hover to any component , I am not able to get complete content for that component, some part got hidden
>    I think something like this would look clean:
>    image
> 2. For reference:
>    image
>    while clicking on hamburger menu, I think whole navbar if occupies entire viewport width and height  that would look more clean such that when you will click any component , the navbar goes off and displays the content for that particular component.
> 3. Add hover effect on navigation bar li items for visual effect of clicking
> 4. For reference:
>    image
>    The buttons of installation and getStarted if are larger in width, with transparent backgrounds will cover the whitespace and will look visual good
> 
> Though I liked your quirky UI and color theme +that code button looks amazing!

Hello Sakshi,
1. Content hidden under navbar issue has been fixed
2. Yes, now the navbar looking good
3. Hover effect made the library interactive and attractive now
4. Both the buttons on the landing page now are larger with a hover effect

Thanks for your valuable inputs which made the library better now and yes you gotta good UI eyes

**Comment by pruthvirajmv** [comment]
Hello Scopers,
As per the above reveiws, codebase & UI things are updated/fixed
Hence merged to the main
Thanks for the support!

**Pull request merged**
